server:
  port: 8080

spring:
  application:
    name: school-service-life
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 100MB
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      initialization-fail-timeout: 1    # 缩短初始化超时时间
      auto-commit: true
      minimum-idle: 5                   # 最小空闲连接数
      maximum-pool-size: 10             # 最大连接数
      idle-timeout: 30000            # 空闲连接存活最大时间，默认600000（10分钟）
      pool-name: HikariCP
      max-lifetime: 1800000          # 连接的生命时长，超时而且没被使用则被释放（retired），默认:30分钟
      connection-timeout: 30000      # 等待连接池分配连接的最大时长（毫秒）
      connection-test-query: SELECT 1 # 连接测试查询
      connection-init-sql: SELECT 1     # 连接初始化时执行的SQL
      warm-up-enabled: ${spring.datasource.hikari.warm-up-enabled}  # 开发环境开启，生产环境可以关闭

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      database: 0
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      base-url: ${spring.ai.openai.base-url}


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

minio:
  url: ${minio.url}
  accessKey: ${minio.accessKey}
  secretKey: ${minio.secretKey}
  bucketName: ${minio.bucketName}

task:
  pool:
    core-size: 10          # 核心线程数
    max-size: 50           # 最大线程数
    keep-alive: 60         # 空闲线程存活时间
    queue-capacity: 100    # 任务队列容量

logging:
  level:
    com.school.web.mapper: INFO  # 将mapper包的日志级别设置为INFO